lib/project_web/router.ex
defmodule ProjectWeb.Router do
  use ProjectWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ProjectWeb do
    pipe_through :browser

    get "/", LoginController, :show
    post "/", LoginController, :create
    get "/tweets", TweetsController, :index
    get "/log-out", LoginController, :logout
    post "/tweets/subscribe", TweetsController, :subscribe
    post "/tweets/send", TweetsController, :sendTweet
    post "/tweets/retweet", TweetsController, :retweet
    post "/query", TweetsController, :tweetQuery
    get "/query", QueryController, :queryPage
    post "/query/query", QueryController, :searchValue
    post "/query/subscribe", QueryController, :querysubscribe
  end
end

lib/project_web/controllers/query_controller.ex
defmodule ProjectWeb.QueryController do
  use ProjectWeb, :controller

  def queryPage(conn, params) do
    username = Plug.Conn.get_session(conn, :current_user_name)
    reply_atom = Plug.Conn.get_session(conn, :replyatom)
    response = Plug.Conn.get_session(conn, :response)
    value = Plug.Conn.get_session(conn, :value)

    IO.inspect params
    IO.inspect ""
    IO.puts "Showing Feed for #{username}"
    IO.inspect reply_atom
    IO.inspect response
    length = String.length(value)
    user = String.slice(value, 1..length)
    IO.inspect value
    IO.inspect ""
    tweets = nil
    tweets = cond do
      reply_atom == :error ->
        tweets = [%{}]
      reply_atom == :reply ->
        if(String.starts_with?(value, "@")) do
          tweet = getFeed(user)
        else
          tweets = getHashFeed(user)
          {atom, map} = tweets
          if(atom == :reply)do
            map
          else
            [%{}]
          end
        end
      true ->
        [%{}]
    end

    # tweets = getFeed(username)
    IO.inspect reply_atom
    render(conn, "index.html", username: username, tweets: tweets, value: value)
  end

  def querysubscribe(conn, %{"user" => user_name}) do
    #subscribe method
    subscriber = Plug.Conn.get_session(conn, :current_user_name)
    reply = Project.ClientFunctions.subscribeToUser(subscriber, user_name)
    IO.inspect reply

    conn =
      conn
      |> put_flash(:reply, reply)
    redirect(conn, to: Routes.query_path(conn, :queryPage))
  end

  def getFeed(username) do
    userID = Project.TweetFacility.getUserIDFromName(username)
    tweets = Project.TweetFacility.getFeedFromDb(userID)
    tweets = Enum.reverse(tweets)
    IO.inspect(tweets)
    tweets
  end

  def getHashFeed(hashtag) do
    {replyatom, response} = Project.ClientFunctions.getHashTagTweets(hashtag)
    IO.inspect response
    {replyatom, response}
  end

  def searchValue(conn, %{"value" => value}) do
    IO.inspect "Here"
    {replyatom, response} = Project.ClientFunctions.query(value)

    IO.inspect "Reply atom"
    IO.inspect replyatom
    IO.inspect "Reply atom"
    cond do
      replyatom == :error ->
        #something
        conn =
          conn
          |> put_flash(:error, response)
        redirect(conn, to: Routes.query_path(conn, :queryPage))
      replyatom == :reply ->
        username = Plug.Conn.get_session(conn, :current_user_name)
        conn = conn
        |> put_session(:current_user_name, username)
        |> put_session(:replyatom, replyatom)
        |> put_session(:response, response)
        |> put_session(:value, value)
        redirect(conn, to: Routes.query_path(conn, :queryPage))
      true ->
        conn =
          conn
          |> put_flash(:error, "Unmitigated Error (CODE01)")
        redirect(conn, to: Routes.query_path(conn, :queryPage))
    end
  end

end

lib/project_web/views/query_view.ex
defmodule ProjectWeb.QueryView do
  use ProjectWeb, :view
end

lib/project_web/templates/query/index.html.eex
<link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/tweets.css") %>"/>

<div class = "container-fluid">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <%= form_for @conn, Routes.query_path(@conn, :querysubscribe), [class: "form-inline mt-2 mt-md-0 mr-auto"], fn f -> %>
            <%= text_input f, :user, value: "", class: "form-control mr-sm-2" %>
            <%= submit "Subscribe", class: "btn btn-success" %>
        <% end %>
        
        <%= form_for @conn, Routes.query_path(@conn, :searchValue), [class: "form-inline mt-2 mt-md-0 mr-auto"], fn f -> %>
            <%= text_input f, :value, value: "", class: "form-control mr-sm-2" %>
            <%= submit "Query", class: "btn btn-success" %>
        <% end %>
        <div class="mr-0">
            <label class="navbar-brand"><a class="h4 text-center align-middle text-white" href="/tweets">Home</a></label>
            <%= link "Log Out", to:  Routes.login_path(@conn, :logout), class: "btn btn-danger" %>
        </div>
    </nav>
      
    <p class="alert alert-info text-center" role="alert"><%= get_flash(@conn, :reply) %>
    <%= get_flash(@conn, :error) %></p>
    <div class="row">
        <div class = "col-3 bg-white"></div>
        <div class="col-6 bg-white">
            <div>
                <p class="h2">Feed for "<%= @value %>" </p>
                <br/>
            </div>
            <div class ="scrollable">
                <ul class="list-group">
                <%= for item <- @tweets do %>
                    <div class="card mb-2 bg-light">
                    <div class="card-body">
                        <div class="card-title text-capitalize font-weight-bold">
                        <%= item.owner %>
                            <%= form_for @conn, Routes.tweets_path(@conn, :retweet), fn f -> %>
                            <%= hidden_input f, :tweetid, value: item.tweetid %>
                            <%= submit "Retweet", class: "btn btn-outline-warning float-right" %>
                        <% end %>
                        </div>
                        <div class="card-text">
                        <%= item.tweet %>
                        </div>
                    </div>
                    </div>
                <% end %>
                </ul>
            </div>
            </div>
            <div class="w-100"></div>
            <div class= "col bg-white">
            <br/>
            <br/>
            <br/>
            </div>
        <div class = "col-3 bg-white"></div>
    </div> 
</div>